// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class ConsultationSchedule : IEntityBase
{
    public int ConsultationScheduleId { get; set; }

    public int? ConsultationFormId { get; set; }

    public int? NurseId { get; set; }

    public int? Status { get; set; }

    public string Location { get; set; }

    public DateTime? ConsultDate { get; set; }

    public virtual ConsultationForm ConsultationForm { get; set; }

    public virtual Nurse Nurse { get; set; }
}