// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class ConsentForm : IEntityBase
{
    public int ConsentFormId { get; set; }

    public int? ParentId { get; set; }

    public int? ManagerId { get; set; }

    public DateTime? ConfirmDateTime { get; set; }

    public bool? IsConfirmed { get; set; }

    public virtual Manager Manager { get; set; }

    public virtual Parent Parent { get; set; }
}