// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class ConsultationForm : IEntityBase
{
    public int ConsultationFormId { get; set; }

    public int? ParentId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<ConsultationSchedule> ConsultationSchedules { get; set; } = new List<ConsultationSchedule>();

    public virtual Parent Parent { get; set; }
}