// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class HealthCheckResult : IEntityBase
{
    public int HealthCheckResultId { get; set; }

    public int? HealthCheckScheduleId { get; set; }

    public int? HealthProfileId { get; set; }

    public int? NurseId { get; set; }

    public double? Height { get; set; }

    public double? Weight { get; set; }

    public string LeftEyeVision { get; set; }

    public string RightEyeVision { get; set; }

    public string Note { get; set; }

    public virtual HealthCheckSchedule HealthCheckSchedule { get; set; }

    public virtual HealthProfile HealthProfile { get; set; }

    public virtual Nurse Nurse { get; set; }
}